### ISSUE TITLE
PC works fine, but NPCs don't

### ISSUE THREAD

**Issue by Minizbot2012** [aedenthorn/fuzrobork#1]
Windows Version: Windows 10 Pro
Configs tested: PC voice on and off, and Skip empty Responses on and off, voices all set to 409
Mod Manager: Mod Organizer
MsPerWordSilence is 500
Other Notes:
SKSE is version 1.7.3
skse.log Outputs that the plugin has loaded successfully, however there is no further output.

**Comment by aedenthorn** [comment]
Are you referring to the case where NPC dialogue is already voiced, or only when it is unvoiced? This mod only works for custom unvoiced dialogue.

**Comment by Minizbot2012** [comment]
It is unvoiced audio.

**Comment by Minizbot2012** [comment]
I've gotten it to work with 10.1, I'm going to close this.
